---
sidebar: sidebar 
permalink: use/task-manage-fsx-volumes.html 
keywords: fsx for ontap, fsx, aws, delete volumes, delete nfs volumes, delete cifs volumes, tiering policy, mount path, get mount path, mount volume, delete volumes, snapshots, edit volume, clone volume, clone 
summary: 您可以使用BlueXP管理卷、克隆和快照、并更改适用于ONTAP 的FSX的分层策略。 
---
= 管理适用于 ONTAP 的 Amazon FSX 的卷
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用BlueXP查看和管理卷、克隆和快照、以及更改适用于ONTAP 的FSX的分层策略。



== 查看卷详细信息

创建卷后、您可以查看配置详细信息。

. 打开工作环境。
+

NOTE: 您可以将鼠标悬停在卷名称上以显示卷类型。

. 打开卷选项卡并选择*管理卷*以打开*卷操作*菜单。
. 选择*查看卷详细信息*。




== 编辑卷

创建卷后，您可以随时对其进行修改。

.步骤
. 打开工作环境。
. 打开卷选项卡并选择*管理卷*以打开*卷操作*菜单。
. 选择*编辑卷设置*。
+
.. 对于 NFS ，您可以修改大小和标记。
.. 对于 CIFS ，您可以根据需要修改共享名称，用户，权限和 Snapshot 策略。


. 选择 * 应用 * 。




== 克隆卷

创建卷后，您可以从新 Snapshot 创建新的读写卷。

.步骤
. 打开工作环境。
. 打开卷选项卡并选择*管理卷*以打开*卷操作*菜单。
. 选择*克隆卷*。
. 输入克隆卷的名称。
. 选择 * 克隆 * 。




== 管理 Snapshot 副本

Snapshot 副本可为卷提供时间点副本。创建 Snapshot 副本并将数据还原到新卷。

.步骤
. 打开工作环境。
. 打开卷选项卡并选择*管理卷*以打开*保护操作*菜单。
. 选择一个可用选项来管理Snapshot副本：
+
** * 创建 Snapshot 副本 *
** * 从 Snapshot 副本还原 *


. 按照提示完成选定操作。




== 更改分层策略

更改卷的分层策略。

.步骤
. 打开工作环境。
. 打开卷选项卡并选择*管理卷*以打开*高级操作*菜单。
. 选择*更改分层策略*。
. 选择一个新的卷分层策略，然后单击 * 更改 * 。




== 复制和同步数据

您可以使用BlueXP在存储环境之间复制数据。要为 ONTAP 复制配置 FSX ，请参见 https://docs.netapp.com/us-en/cloud-manager-replication/task-replicating-data.html["在系统之间复制数据"^]。

您可以在BlueXP中使用Cloud Sync 创建同步关系。要配置同步关系，请参见 https://docs.netapp.com/us-en/cloud-manager-sync/task-creating-relationships.html["创建同步关系"^]。



== 删除卷

删除不再需要的卷。

您不能使用BlueXP删除先前属于SnapMirror关系的卷。必须使用 AWS 管理控制台或命令行界面删除 SnapMirror 卷。

.步骤
. 打开工作环境。
. 打开卷选项卡并选择*管理卷*以打开*卷操作*菜单。
. 选择*删除卷*。
. 输入工作环境名称并确认要删除此卷。从BlueXP中完全删除卷可能需要长达一个小时的时间。



NOTE: 如果您尝试删除克隆的卷，则会收到错误。
