---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: Amazon FSx for NetApp ONTAP是一项完全托管的服务、允许客户启动和运行由NetApp的ONTAP存储操作系统提供支持的文件系统。 
---
= 了解适用于NetApp ONTAP 的Amazon FSX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["适用于 NetApp ONTAP 的 Amazon FSX"^] 是一项完全托管的服务、允许客户启动和运行由NetApp ONTAP存储操作系统提供支持的文件系统。FSX for ONTAP 提供了与 NetApp 客户在内部使用的相同的特性，性能和管理功能，并具有原生 AWS 服务的简单性，灵活性，安全性和可扩展性。



== 在BlueXP  中使用FSx for ONTAP

在BlueXP  画布中、您可以创建和发现FSx for ONTAP工作环境、并使用System Manager和其他BlueXP  服务。如果要管理FSx for ONTAP工作环境和在Amazon FSx for NetApp ONTAP上运行的工作负载，请使用 https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["BlueXP  工作负载工厂"^]。

link:../use/task-creating-fsx-working-environment.html["了解如何在BlueXP  中创建和发现FSx for ONTAP工作环境"^](英文)



== 功能

* 无需配置或管理存储设备，软件或备份。
* 支持CIFS、iSCSI、NFSv3、NFSv4.x https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html["S3"^]和SMB v2.0 - v3.1.1协议。
* 使用可用的不常访问（ IA ）存储层，可实现低成本，几乎无限制的数据存储容量。
* 经过认证，可在延迟敏感型应用程序上运行，包括 Oracle RAC 。
* 可选择捆绑定价和按需购买定价




== BlueXP中的其他功能

* 在_standard_模式下使用BlueXP  时、支持FSx for ONTAP、此模式可利用BlueXP  SaaS层提供完整功能。不支持_Restricted_模式和_Private模式。
+
请参见 link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP部署模式"^] 有关详细信息 ...

* 使用 link:https://docs.netapp.com/us-en/bluexp-family/["BlueXP"^] 作为AWS中的连接器、您可以创建和管理卷、复制数据以及将FSx for ONTAP与NetApp云服务(例如BlueXP分类和BlueXP复制和同步)集成。
* BlueXP分类功能采用人工智能(AI)驱动的技术、可帮助您了解数据上下文并识别驻留在FSx for ONTAP帐户中的敏感数据。 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["了解更多信息。"^]。
* 通过BlueXP复制和同步、您可以自动将数据迁移到云中或内部的任何目标。 https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["了解更多信息。"^]




== 连接器和链路解锁所有FSx for ONTAP功能

通过连接器和链路、可以在BlueXP  和Amazon FSx for NetApp ONTAP工作环境之间建立连接和信任关系。BlueXP  连接器是在云或内部网络中运行的NetApp软件、其链接使用AWS Lamba执行NetApp代码。您不需要连接器或链接即可开始使用BlueXP  或创建FSx for ONTAP工作环境、但您需要使用连接器或链接来充分利用FSx for ONTAP功能。

要使用以下功能、您需要一个连接器或链接：

* 显示FSx for ONTAP文件系统上安装的ONTAP版本
* 管理系统上的iSCSI卷
* 为卷启用和禁用自动增长功能
* 创建和管理Snapshot策略
* 配置复制关系并在文件系统之间复制卷
* 配置备份关系并将卷数据备份到云存储
* 克隆文件系统中的卷
* 直接从ONTAP显示其他指标(默认指标由Amazon CloudWatch收集)
* 管理NFS导出策略


详细了解连接器和链路以及应在何时使用它们：

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["了解有关连接器的更多信息"^](英文)
* https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["了解有关链接的更多信息"^](英文)




== 成本

您的FSX for ONTAP 帐户由AWS维护、而不是由BlueXP维护。请参见 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["《适用于NetApp ONTAP 的Amazon FSX入门指南》"^]。

在AWS中使用Connector和可选数据服务(例如BlueXP复制和同步以及BlueXP分类)会产生额外的成本。



== 支持的区域

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["查看支持的 Amazon 地区。"^]



== 获取帮助

适用于NetApp ONTAP 的Amazon FSX是AWS第一方解决方案。如有与您的FSx for ONTAP文件系统、基础架构或使用此服务的任何解决方案相关的问题或技术支持问题、请使用AWS管理控制台中的支持中心创建AWS支持案例。选择"FSX for ONTAP "服务和相应的类别。提供创建 AWS 支持案例所需的其余信息。

有关BlueXP或BlueXP存储解决方案和服务的一般问题、您可以从在线BlueXP聊天开始。

对于特定于BlueXP  或BlueXP  存储解决方案和服务的技术支持问题、您可以使用您的NetApp组织级别序列号创建BlueXP  支持服务单。您需要link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/support/task-support-registration.html["注册您的BlueXP  组织"^]激活支持。
