---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: 适用于NetApp ONTAP 的Amazon FSX是一项完全托管服务、允许客户启动和运行由NetApp ONTAP 存储操作系统提供支持的文件系统。FSX for ONTAP 提供了与 NetApp 客户目前在内部使用的相同的特性，性能和管理功能，并具有原生 AWS 服务的精简性，灵活性，安全性和可扩展性。 
---
= 了解适用于NetApp ONTAP 的Amazon FSX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["适用于 NetApp ONTAP 的 Amazon FSX"^] 是一项完全托管的服务，允许客户启动和运行由 NetApp ONTAP 存储操作系统提供支持的文件系统。FSX for ONTAP 提供了与 NetApp 客户在内部使用的相同的特性，性能和管理功能，并具有原生 AWS 服务的简单性，灵活性，安全性和可扩展性。



== 功能

* 无需配置或管理存储设备，软件或备份。
* 支持 CIFS ， NFSv3 ， NFSv4.x 和 SMB v2.0 - v3.1.1 协议。
* 使用可用的不常访问（ IA ）存储层，可实现低成本，几乎无限制的数据存储容量。
* 经过认证，可在延迟敏感型应用程序上运行，包括 Oracle RAC 。
* 可选择捆绑定价和按需购买定价




== BlueXP中的其他功能

* 在_standard_或_Restricted_模式下使用BlueXP时、支持Amazon FSx for NetApp ONTAP。
+
** 标准模式利用BlueXP SaaS层提供完整功能。
** 受限模式适用于具有连接限制的组织。
+
请参见 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-modes.html["BlueXP部署模式"^] 有关详细信息 ...



* 使用 link:https://docs.netapp.com/us-en/cloud-manager-family/["BlueXP"^] (Cloud Manager)和AWS中的Connector、您可以创建和管理卷、复制数据、以及将FSx for ONTAP与NetApp云服务(例如BlueXP分类和BlueXP复制和同步(Cloud Sync))集成。
* BlueXP分类(Cloud Data Sense)采用人工智能(AI)驱动的技术、可帮助您了解数据上下文并识别驻留在FSx for ONTAP帐户中的敏感数据。 https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html["了解更多信息。"^]。
* 通过BlueXP复制和同步、您可以自动将数据迁移到云中或内部的任何目标。 https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["了解更多信息。"^]




== 成本

您的FSX for ONTAP 帐户由AWS维护、而不是由BlueXP维护。请参见 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["《适用于NetApp ONTAP 的Amazon FSX入门指南》"^]。

在AWS中使用Connector和可选数据服务(例如BlueXP复制和同步以及BlueXP分类)会产生额外的成本。



== 支持的区域

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["查看支持的 Amazon 地区。"^]



== 获取帮助

适用于NetApp ONTAP 的Amazon FSX是AWS第一方解决方案。对于与您的Amazon FSX for NetApp ONTAP 文件系统、基础架构或任何使用此服务的解决方案 相关的问题或技术支持问题、请使用AWS控制台中的支持中心创建AWS支持案例。选择 "FSX for ONTAP " 服务和相应的类别。提供创建 AWS 支持案例所需的其余信息。

有关BlueXP或BlueXP存储解决方案和服务的一般问题、您可以从在线BlueXP聊天开始。

对于特定于BlueXP或BlueXP存储解决方案和服务的技术支持问题、您可以使用您的BlueXP帐户级别序列号打开NetApp支持服务单。您需要 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/support/task-support-registration.html["注册您的BlueXP帐户"^] 激活支持。
